# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-03 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(default=b'Null', max_length=100)),
                ('Description', models.CharField(default=b'Null', max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('images', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'Null', max_length=100)),
                ('numberofbedroom', models.IntegerField(default=b'Null')),
                ('Description', models.CharField(default=b'Null', max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('images', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='SavedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userid', models.CharField(default=b'Null', max_length=100)),
                ('Display_id', models.IntegerField(default=b'Null')),
            ],
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
    ]
